package com.grv.junit;

import java.io.IOException;

import javax.xml.parsers.ParserConfigurationException;

import junit.framework.TestCase;

import org.junit.Test;
import org.xml.sax.SAXException;

import com.grv.xml.XMLValidator;

/**
 * The class <code>XMLValidatorTest</code> contains tests for the class {@link <code>XMLValidator</code>}
 * 
 * @pattern JUnit Test Case
 * 
 * @generatedBy CodePro at 9/06/12 1:41 PM
 * 
 * @author gauravve
 * 
 * @version $Revision$
 */
public class XMLValidatorTest extends TestCase {

    /**
     * Construct new test instance
     * 
     * @param name
     *            the test name
     */
    public XMLValidatorTest(String name) {
	super(name);
    }

    /**
     * Perform pre-test initialization
     * 
     * @throws Exception
     * 
     * @see TestCase#setUp()
     */
    @Override
    protected void setUp() throws Exception {
	super.setUp();
	// Add additional set up code here
    }

    /**
     * Perform post-test clean up
     * 
     * @throws Exception
     * 
     * @see TestCase#tearDown()
     */
    @Override
    protected void tearDown() throws Exception {
	super.tearDown();
	// Add additional tear down code here
    }

    @Test
    public void testValidateAseXMLIncorrectR16() {
	XMLValidator validator = new XMLValidator();
	try {
	    validator.validateSchema("aseXMLR17/aseXML_r17.xsd", "asexml16.xml");
	} catch (IOException e) {
	    fail();
	} catch (SAXException e) {
	    fail();
	} catch (ParserConfigurationException e) {
	    fail();
	}
    }

    @Test
    public void testValidateAseXMLR16() {
	XMLValidator validator = new XMLValidator();
	try {
	    validator.validateSchema("aseXMLR16/aseXML_r16.xsd", "asexml16.xml");
	} catch (IOException e) {
	    fail();
	} catch (SAXException e) {
	    fail();
	} catch (ParserConfigurationException e) {
	    fail();
	}

    }

    @Test
    public void testValidateAseXMLR17() {
	XMLValidator validator = new XMLValidator();
	try {
	    validator.validateSchema("aseXMLR17/aseXML_r17.xsd", "asexml17.xml");
	} catch (IOException e) {
	    fail();
	} catch (SAXException e) {
	    fail();
	} catch (ParserConfigurationException e) {
	    fail();
	}
    }
}

/*
 * $CPS$ This comment was generated by CodePro. Do not edit it. patternId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern strategyId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = assertTrue = false callTestMethod = true createMain =
 * false createSetUp = true createTearDown = true createTestFixture = false
 * createTestStubs = false methods = package = com.grv.junit
 * package.sourceFolder = xslUI/src superclassType = junit.framework.TestCase
 * testCase = XMLValidatorTest testClassType = com.grv.xml.XMLValidator
 */